# 1. 允許所有來源連線 (因為 Docker 網路會幫我們隔離，所以綁定 0.0.0.0 是安全的)
bind 0.0.0.0

# 2. 開啟保護模式 (要求密碼才能連線，企業資安標準)
protected-mode yes

# 3. 設定連線密碼 (未來的 Puma 必須帶著這個密碼才能存資料)
requirepass gitlab_redis_secret

# 4. 關閉背景守護行程模式 (極度重要！Docker 容器的應用程式必須跑在前景，否則容器會立刻死掉)
daemonize no
